#pragma once
#include "third-party/cjson/cJSON.h"
#include "third-party/sqlite/sqlite3.h"
#include "database.h"
#include "types.h"
#include <stdio.h>
#include <string.h>
void output_student_data(void);
void output_student_with_sql(void);
void display_sort_menu(void);
void display_delete_menu(void);
void display_stat(void);